### ISSUE TITLE
Not runnable

### ISSUE THREAD

**Issue by Divide-By-0** [clethrill/WitsAndWagers#1]
I need to do `meteor update --release METEOR@2.12`. After that, `meteor --settings settings/example.json` gives 
```
=> Errors prevented startup:                  
   
   While preparing to run:
   settings/example.json: file not found (settings file)
   
```

**Comment by clethrill** [comment]
Hey this was a private repo that is incomplete and hasn't been touched in 7 years. Not sure why it's public by I will be removing it.
